/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package pl.gsmservice.gateway.models.operations;

import java.lang.Exception;
import java.lang.Long;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import pl.gsmservice.gateway.models.components.SenderInput;
import pl.gsmservice.gateway.utils.Options;

public class SDKMethodInterfaces {


    public interface MethodCallGetAccountDetails {
        GetAccountDetailsResponse get(
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallGetSubaccountDetails {
        GetSubaccountDetailsResponse getSubaccount(
            String userLogin,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallGetMessages {
        GetMessagesResponse getByIds(
            List<Long> ids,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallCancelMessages {
        CancelMessagesResponse cancelScheduled(
            List<Long> ids,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallListMessages {
        ListMessagesResponse list(
            Optional<Long> page,
            Optional<Long> limit,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallGetMmsPrice {
        GetMmsPriceResponse getPrice(
            GetMmsPriceRequestBody request,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallSendMms {
        SendMmsResponse send(
            SendMmsRequestBody request,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallGetSmsPrice {
        GetSmsPriceResponse getPrice(
            GetSmsPriceRequestBody request,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallSendSms {
        SendSmsResponse send(
            SendSmsRequestBody request,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallListIncomingMessages {
        ListIncomingMessagesResponse list(
            Optional<Long> page,
            Optional<Long> limit,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallGetIncomingMessages {
        GetIncomingMessagesResponse getByIds(
            List<Long> ids,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallPing {
        PingResponse ping(
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallListSenders {
        ListSendersResponse list(
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallAddSender {
        AddSenderResponse add(
            SenderInput request,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallDeleteSender {
        DeleteSenderResponse delete(
            String sender,
            Optional<Options> options) throws Exception;
    }


    public interface MethodCallSetDefaultSender {
        SetDefaultSenderResponse setDefault(
            String sender,
            Optional<Options> options) throws Exception;
    }


}
