/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package pl.gsmservice.gateway.models.components;


import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import pl.gsmservice.gateway.utils.OneOfDeserializer;
import pl.gsmservice.gateway.utils.TypedObject;
import pl.gsmservice.gateway.utils.Utils.JsonShape;
import pl.gsmservice.gateway.utils.Utils.TypeReferenceWithShape;
import pl.gsmservice.gateway.utils.Utils;

/**
 * Attachments - Attachments for the message. You can pass here images, audio and video files bodies. To set one attachment please use <code>Attachments.of(String)</code> method simply passing to it a <code>string</code> with attachment body encoded by <code>base64</code>. To set multiple attachments please use <code>Attachments.of(List.of(String,...))</code> method passing to it <code>List&lt;string&gt;</code> with attachments bodies encoded by <code>base64</code>. Max 3 attachments per message.
 */

@JsonDeserialize(using = Attachments._Deserializer.class)
public class Attachments {

    @JsonValue
    private TypedObject value;
    
    private Attachments(TypedObject value) {
        this.value = value;
    }

    public static Attachments of(String value) {
        Utils.checkNotNull(value, "value");
        return new Attachments(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<String>(){}));
    }

    public static Attachments of(List<String> value) {
        Utils.checkNotNull(value, "value");
        return new Attachments(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<String>>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code java.lang.String}</li>
     * <li>{@code java.util.List<java.lang.String>}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Attachments other = (Attachments) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Attachments> {

        public _Deserializer() {
            super(Attachments.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<String>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Attachments.class,
                "value", value);
    }
 
}
