/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package pl.gsmservice.gateway.models.components;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MessageType - Message type (SmsType.SmsPro -&gt; SMS PRO, SmsType.SmsEco -&gt; SMS ECO, SmsType.SmsTwoWay -&gt;SMS 2WAY, SmsType.Mms -&gt; MMS)
 */
public enum MessageType {
    SmsPro(1L),
    SmsEco(3L),
    SmsTwoWay(4L),
    Mms(10L);

    @JsonValue
    private final long value;

    private MessageType(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
}
