/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package pl.gsmservice.gateway.models.components;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * MessageType - Message type according to the table:
 *     
 * |type|Description|
 * |----|-----------|
 * |  1 | SMS PRO   |
 * |  3 | SMS ECO   |
 * |  4 | SMS 2WAY  |
 * | 10 | MMS       |
 */
public enum MessageType {
    SmsPro(1L),
    SmsEco(3L),
    SmsTwoWay(4L),
    Mms(10L);

    @JsonValue
    private final long value;

    private MessageType(long value) {
        this.value = value;
    }
    
    public long value() {
        return value;
    }
}
