/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package pl.gsmservice.gateway.models.components;


import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;
import pl.gsmservice.gateway.utils.OneOfDeserializer;
import pl.gsmservice.gateway.utils.TypedObject;
import pl.gsmservice.gateway.utils.Utils.JsonShape;
import pl.gsmservice.gateway.utils.Utils.TypeReferenceWithShape;
import pl.gsmservice.gateway.utils.Utils;

/**
 * Recipients - The recipient number or multiple recipients numbers of single message. To set one recipient, simply pass here a `string` with his phone number. To set multiple recipients, pass here a simple `array` of `string`. Optionally you can also set custom id (user identifier) for each message - pass `PhoneNumberWithCid` object (in case of single recipient) or `Array` of `PhoneNumberWithCid` (in case of multiple recipients).
 */

@JsonDeserialize(using = Recipients._Deserializer.class)
public class Recipients {

    @JsonValue
    private TypedObject value;
    
    private Recipients(TypedObject value) {
        this.value = value;
    }

    public static Recipients of(String value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<String>(){}));
    }

    public static Recipients of(List<?> value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<?>>(){}));
    }

    public static Recipients of(PhoneNumberWithCid value) {
        Utils.checkNotNull(value, "value");
        return new Recipients(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<PhoneNumberWithCid>(){}));
    }

    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code java.lang.String}</li>
     * <li>{@code java.util.List<java.lang.String>}</li>
     * <li>{@code pl.gsmservice.gateway.models.components.PhoneNumberWithCid}</li>
     * <li>{@code java.util.List<pl.gsmservice.gateway.models.components.PhoneNumberWithCid>}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Recipients other = (Recipients) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<Recipients> {

        public _Deserializer() {
            super(Recipients.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<PhoneNumberWithCid>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<List<String>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<PhoneNumberWithCid>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Recipients.class,
                "value", value);
    }
 
}
